# Generated by Django 4.1.7 on 2023-10-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ndehistoriaclinica', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('Fechadenacimiento', models.DateField()),
                ('Enfermedad', models.CharField(choices=[('Cardiovascular', 'Cardiovascular'), ('Oncología', 'Oncología'), ('EnfermedadesInfecciosas', 'Enfermedades Infecciosas'), ('Psiquiatría', 'Psiquiatría')], max_length=255)),
                ('otrasenfermedades', models.TextField(blank=True)),
                ('tratamiento', models.CharField(choices=[('Clopidogrel', 'Clopidogrel'), ('Simvastatina', 'Simvastatina'), ('Atorvastatina', 'Atorvastatina')], max_length=255)),
                ('genotipos', models.CharField(choices=[('CYP2C19', 'CYP2C19'), ('SLCO1B1', 'SLCO1B1')], max_length=255)),
            ],
        ),
    ]
