# Generated by Django 4.1.7 on 2023-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Enfermedad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Ndehistoriaclinica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genotipos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otrasenfermedades',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tratamiento',
            field=models.CharField(max_length=100),
        ),
    ]
